export const bgColors: Record<string, string> = {
  all: 'bg-gradient-to-b from-gray-500 to-gray-600',
  grass: 'bg-gradient-to-b from-green-700 to-green-800',
  normal: 'bg-gradient-to-b from-gray-700 to-gray-800',
  fire: 'bg-gradient-to-b from-orange-700 to-orange-800',
  water: 'bg-gradient-to-b from-blue-700 to-blue-800',
  electric: 'bg-gradient-to-b from-yellow-500 to-yellow-600',
  ice: 'bg-gradient-to-b from-teal-700 to-teal-800',
  fighting: 'bg-gradient-to-b from-red-700 to-red-800',
  poison: 'bg-gradient-to-b from-purple-700 to-purple-800',
  ground: 'bg-gradient-to-b from-amber-700 to-amber-800',
  flying: 'bg-gradient-to-b from-indigo-700 to-indigo-800',
  psychic: 'bg-gradient-to-b from-pink-700 to-pink-800',
  bug: 'bg-gradient-to-b from-lime-700 to-lime-800',
  rock: 'bg-gradient-to-b from-amber-800 to-amber-900',
  ghost: 'bg-gradient-to-b from-indigo-700 to-indigo-800',
  dragon: 'bg-gradient-to-b from-purple-700 to-purple-800',
  dark: 'bg-gradient-to-b from-black to-black',
  steel: 'bg-gradient-to-b from-gray-500 to-gray-600',
  fairy: 'bg-gradient-to-b from-pink-700 to-pink-800',
}
