export const focusColors: Record<string, string> = {
  all: 'bg-gradient-to-b from-gray-600 to-gray-300',
  grass: 'bg-gradient-to-b from-green-800 to-green-500',
  normal: 'bg-gradient-to-b from-gray-800 to-gray-500',
  fire: 'bg-gradient-to-b from-orange-800 to-orange-500',
  water: 'bg-gradient-to-b from-blue-800 to-blue-500',
  electric: 'bg-gradient-to-b from-yellow-600 to-yellow-300',
  ice: 'bg-gradient-to-b from-teal-800 to-teal-500',
  fighting: 'bg-gradient-to-b from-red-800 to-red-500',
  poison: 'bg-gradient-to-b from-purple-800 to-purple-500',
  ground: 'bg-gradient-to-b from-amber-800 to-amber-500',
  flying: 'bg-gradient-to-b from-indigo-800 to-indigo-500',
  psychic: 'bg-gradient-to-b from-pink-800 to-pink-500',
  bug: 'bg-gradient-to-b from-lime-800 to-lime-500',
  rock: 'bg-gradient-to-b from-amber-900 to-amber-500',
  ghost: 'bg-gradient-to-b from-indigo-800 to-indigo-500',
  dragon: 'bg-gradient-to-b from-purple-800 to-purple-500',
  dark: 'bg-gradient-to-b from-black to-black',
  steel: 'bg-gradient-to-b from-gray-600 to-gray-300',
  fairy: 'bg-gradient-to-b from-pink-800 to-pink-500',
}
