export const hoverColors: Record<string, string> = {
  all: 'hover:bg-gray-400',
  grass: 'hover:bg-green-600',
  normal: 'hover:bg-gray-500',
  fire: 'hover:bg-orange-600',
  water: 'hover:bg-blue-600',
  electric: 'hover:bg-yellow-400',
  ice: 'hover:bg-teal-600',
  fighting: 'hover:bg-red-600',
  poison: 'hover:bg-purple-600',
  ground: 'hover:bg-amber-600',
  flying: 'hover:bg-indigo-600',
  psychic: 'hover:bg-pink-600',
  bug: 'hover:bg-lime-600',
  rock: 'hover:bg-amber-700',
  ghost: 'hover:bg-indigo-600',
  dragon: 'hover:bg-purple-600',
  dark: 'hover:bg-black',
  steel: 'hover:bg-gray-400',
  fairy: 'hover:bg-pink-600',
}
